/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LinkTest {
        "link": string;
    }
    interface TestWithOptionalSlot {
        /**
          * enables or disables slot
         */
        "useSlot": boolean;
    }
    interface TestWithSlot {
    }
    interface TestWithoutSlot {
    }
}
declare global {
    interface HTMLLinkTestElement extends Components.LinkTest, HTMLStencilElement {
    }
    var HTMLLinkTestElement: {
        prototype: HTMLLinkTestElement;
        new (): HTMLLinkTestElement;
    };
    interface HTMLTestWithOptionalSlotElement extends Components.TestWithOptionalSlot, HTMLStencilElement {
    }
    var HTMLTestWithOptionalSlotElement: {
        prototype: HTMLTestWithOptionalSlotElement;
        new (): HTMLTestWithOptionalSlotElement;
    };
    interface HTMLTestWithSlotElement extends Components.TestWithSlot, HTMLStencilElement {
    }
    var HTMLTestWithSlotElement: {
        prototype: HTMLTestWithSlotElement;
        new (): HTMLTestWithSlotElement;
    };
    interface HTMLTestWithoutSlotElement extends Components.TestWithoutSlot, HTMLStencilElement {
    }
    var HTMLTestWithoutSlotElement: {
        prototype: HTMLTestWithoutSlotElement;
        new (): HTMLTestWithoutSlotElement;
    };
    interface HTMLElementTagNameMap {
        "link-test": HTMLLinkTestElement;
        "test-with-optional-slot": HTMLTestWithOptionalSlotElement;
        "test-with-slot": HTMLTestWithSlotElement;
        "test-without-slot": HTMLTestWithoutSlotElement;
    }
}
declare namespace LocalJSX {
    interface LinkTest {
        "link"?: string;
    }
    interface TestWithOptionalSlot {
        /**
          * enables or disables slot
         */
        "useSlot"?: boolean;
    }
    interface TestWithSlot {
    }
    interface TestWithoutSlot {
    }
    interface IntrinsicElements {
        "link-test": LinkTest;
        "test-with-optional-slot": TestWithOptionalSlot;
        "test-with-slot": TestWithSlot;
        "test-without-slot": TestWithoutSlot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "link-test": LocalJSX.LinkTest & JSXBase.HTMLAttributes<HTMLLinkTestElement>;
            "test-with-optional-slot": LocalJSX.TestWithOptionalSlot & JSXBase.HTMLAttributes<HTMLTestWithOptionalSlotElement>;
            "test-with-slot": LocalJSX.TestWithSlot & JSXBase.HTMLAttributes<HTMLTestWithSlotElement>;
            "test-without-slot": LocalJSX.TestWithoutSlot & JSXBase.HTMLAttributes<HTMLTestWithoutSlotElement>;
        }
    }
}
